### ISSUE TITLE
Find suitable template

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/roompillow-web#1]

**Comment by russel0907** [comment]
Fine suitable template;

## Template 1
![Screenshot 2022-04-25 at 11-32-20 unapp Template](https://user-images.githubusercontent.com/94702093/165016488-a2cf6e45-7e94-4fcd-a48f-a81f1351e37d.png)
https://technext.github.io/unapp/

## Template 2
![Screenshot 2022-04-25 at 11-32-46 Lifetrakr](https://user-images.githubusercontent.com/94702093/165016523-dd886f8f-1360-4b16-8779-514c5a91a996.png)
https://technext.github.io/lifetrakr/

## Template 3
![Screenshot 2022-04-25 at 11-32-57 EduWell - Education HTML5 Template](https://user-images.githubusercontent.com/94702093/165016552-28bc6e4b-5274-4cd1-a453-41a59beaeff0.png)
https://technext.github.io/eduwell/index.html

## Template 4
![Screenshot 2022-04-25 at 11-33-20 WebApp — Website Template by Colorlib](https://user-images.githubusercontent.com/94702093/165016576-47f0e712-9804-4bcd-9121-38342da9d968.png)
https://technext.github.io/webapp/index.html

## Template 5
![Screenshot 2022-04-25 at 11-33-32 Mosh - Creative Business Template Home](https://user-images.githubusercontent.com/94702093/165016593-a57033bc-9481-42f6-9628-5a774101e3b5.png)
https://technext.github.io/mosh/index.html

## Template 6
![Screenshot 2022-04-25 at 11-33-43 Colorlib App - App Landing Page](https://user-images.githubusercontent.com/94702093/165016609-d3e885e2-ad60-4d2a-be5b-695c441522da.png)
https://technext.github.io/CA/index.html

**Comment by rosclaritha** [comment]
@russel0907 Proceed with Template 1:
https://technext.github.io/unapp/
