### ISSUE TITLE
Update icon color to white

### ISSUE THREAD

**Issue by paragasu** [phisoft/roompillow-web#11]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/27353/168981853-85ce595a-70f2-4f88-a3f9-2d2f40aebd1a.png">

**Comment by russel0907** [comment]
## Update icon tab color to white

![Screenshot (330)](https://user-images.githubusercontent.com/94702093/169000820-6f627f3b-a031-4a11-8fa5-826bbfbeec78.png)
