### ISSUE TITLE
Redesign channel list

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/roompillow-web#13]
Redesign the list to make it brighter, not red.
![image](https://user-images.githubusercontent.com/30463117/169432712-c5c7eec8-dab4-4e84-9295-e276db39f2bd.png)

**Comment by russel0907** [comment]
# Redesign Channel List;

## change cover image and make overlay color brighter. 

![Screenshot 2022-05-20 at 11-27-57 Roompillow - PMS for Backpacker Hostels](https://user-images.githubusercontent.com/94702093/169444815-9f5f5688-97e1-48f4-9138-f81618aec424.png)
