### ISSUE TITLE
Remove channel

### ISSUE THREAD

**Issue by paragasu** [phisoft/roompillow-web#18]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/169966100-716ea8c3-daec-407c-8545-a03ba630201b.png">

**Comment by niwle** [comment]
Removed channel:
![removed channel](https://user-images.githubusercontent.com/61690172/169984091-d16da292-2fd0-4cea-b38f-f0e3e7f9f8cb.png)
