### ISSUE TITLE
Remove backpackers hostel

### ISSUE THREAD

**Issue by paragasu** [phisoft/roompillow-web#19]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/169966227-19c2882e-18c9-4774-9e6c-30afc519d719.png">

**Comment by russel0907** [comment]
## Removed backpackers hostel 

![Screenshot (345)](https://user-images.githubusercontent.com/94702093/170166199-85d33380-97bf-44c0-b17d-98fccadeaad8.png)
