### ISSUE TITLE
Redesign website

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/roompillow-web#2]
Please refer to issue https://github.com/phisoft/roompillow-web/issues/1 on the template selection.

**Comment by russel0907** [comment]
Redesign website;

![Screenshot 2022-04-27 at 14-06-23 Roompillow - PMS for Backpacker Hostels](https://user-images.githubusercontent.com/94702093/165452148-2810849e-46b3-4b58-b9a1-bd7fd6146bb8.png)
