### ISSUE TITLE
Redesign header 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/roompillow-web#4]
Can view AdobeXD website header as reference: https://www.adobe.com/sea/products/xd.html

![image](https://user-images.githubusercontent.com/30463117/165905357-4057a9c5-e95d-42b6-9fd6-0295e29a6d3d.png)

**Comment by russel0907** [comment]
## Redesign Header;

![Screenshot 2022-05-23 at 09-21-19 Roompillow - PMS for Backpacker Hostels](https://user-images.githubusercontent.com/94702093/169726396-4489dd4e-9df8-450c-84ec-6854ae92a01b.png)
