### ISSUE TITLE
Remove pricing

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/roompillow-web#5]
![image](https://user-images.githubusercontent.com/30463117/165905488-21708b56-b0ce-47b4-92fe-5faa85061153.png)

**Comment by russel0907** [comment]
Remove pricing section;

![Screenshot 2022-05-02 at 20-36-44 Roompillow - PMS for Backpacker Hostels](https://user-images.githubusercontent.com/94702093/166234745-1b57d25c-d043-4cbf-94c5-fa02fb33e708.png)
