### ISSUE TITLE
Redesign footer

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/roompillow-web#6]
Too much unused space, can make column into 3 or decrease the spacing.

![image](https://user-images.githubusercontent.com/30463117/165905885-291d53d5-a950-48ed-b309-79117000e96e.png)

**Comment by russel0907** [comment]
Redesign footer;

make some adjustment on the unused space & column

![Screenshot (295)](https://user-images.githubusercontent.com/94702093/166855020-a203aca6-9e0d-41b8-b506-5fd37615cd8c.png)
