### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by paragasu** [phisoft/roompillow-web#7]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/166101210-0263c9a2-d128-4f1b-be53-9d65bec807c0.png">

**Comment by russel0907** [comment]
Update screenshot header section;

![Screenshot (343)](https://user-images.githubusercontent.com/94702093/169943996-b4209cf8-37a6-4b25-ac84-606b4ca84250.png)
