### ISSUE TITLE
Change screenshots

### ISSUE THREAD

**Issue by paragasu** [phisoft/roompillow-web#8]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/166101241-3ea4f9d1-95bf-4967-8177-764ad0da207b.png">

**Comment by russel0907** [comment]
## Change screenshots on website's content;

![Screenshot 2022-05-24 at 14-34-05 Roompillow - PMS for Backpacker Hostels](https://user-images.githubusercontent.com/94702093/169965009-cc0f1999-cd05-4aa2-b921-9c2f4f000712.png)
